# Generated by Django 4.0.5 on 2022-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
