# Generated by Django 4.0.5 on 2022-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_remove_menu_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='None', upload_to='photos'),
        ),
    ]
